### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by BlockoS** [BlockoS/HuDK#12]
Create a sample makefile with all the necessary options to choose between pceas and cla65

**Comment by freem** [comment]
uploaded my current Makefile [in this commit](https://github.com/BlockoS/HuDK/commit/7d61d4c5bdaba58d808db420d9ef62522dc3f11f)

**Comment by BlockoS** [comment]
A new CMake toolchain was added. I only tested the Makefile generator under Linux at the moment.
