### ISSUE TITLE
HuCard startup code

### ISSUE THREAD

**Issue by BlockoS** [BlockoS/HuDK#5]
Add a minimal HuCard startup code. This means simple irq vectors.
- [x] pceas
- [x] ca65

**Comment by BlockoS** [comment]
Currently working on the pceas version.

**Comment by BlockoS** [comment]
Add a flag to switch between standard and expert mode.
In standard mode, everything is setup to have a ready to use env (bat already set, font loaded, default irq vectors, etc...).
In expert mode, you'll have to write the startup code and set everything up.

**Comment by Fabrizio-Caruso** [comment]
Thanks a lot for your project! I barely understand what it is about...
I guess you are creating an SDK based on CC65 for the PCE.
Sorry to bother you.
I have not been able to figure out how to use CC65 for the PCE target other than building 8k roms.
I would like to understand how you do it but I cannot find any documentation.
I would like to use for my massively multi-system game: 
https://github.com/Fabrizio-Caruso/CROSS-CHASE
Obviously I am only using ANSI C.
